### PR TITLE
Travisci

### PR DESCRIPTION
**Pull request by iankronquist**
1. Add before_script action to travis to install dependencies
2. Run travis tests
3. Add travis badge to README
4. **Bonus** Add .gitignore to ignore node modules

### CODE REVIEW

**Comment by iankronquist** [comment]
The npm which goes with Nodejs 0.8 & 0.6 don't support the `^` syntax used in package.json for the sodium dependency. Why are you targeting old versions of Node? Why not target 0.10 and 0.12?

**Comment by iankronquist** [comment]
Everything is green using Nodejs 0.10: https://travis-ci.org/iankronquist/pull-box-stream/builds/65746636
Travis also fails properly if the tests fail: https://travis-ci.org/iankronquist/pull-box-stream/builds/65746411

**Comment by dominictarr** [comment]
merged. btw I use a .gitignore file but I just don't check it in.
I didn't know you need the before_script command on travis, it seems to work with my other modules just fine.

**Comment by iankronquist** [comment]
You don't need the before_script, I should get rid of that. You should also turn on Travis CI for this repo: http://docs.travis-ci.com/user/getting-started/#Step-two%3A-Activate-GitHub-Webhook

**Pull request merged**
